baseURL: "https://notjonhuang.github.io/" 
title: Jonathan Huang
theme: "PaperMod"

enableInlineShortcodes: true
enableRobotsTXT: true
pagination:
  pagerSize: 20

taxonomies:
    tag: tags

menu:
    main:
        - name: About
          url: about/
          weight: 1
        - name: Publications
          url: papers/
          weight: 2
        - name: Media
          url: media/
          weight: 3
        - name: Resume
          url: cv_jh.pdf
          weight: 4 
        # - name: Photography
        #   url: https://pmichaillat.substack.com
        #   weight: 4

params:
    description: "I am a medical student in the Medical Scientist Training Program at Northwestern University."
    author: Name
    # googleAnalyticsID: "G-XXXXX"
    DateFormat: "January 2006"
    defaultTheme: light
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title: Jonathan Huang, PhD
          subtitle: "I am a medical student in the Medical Scientist Training Program at Northwestern University,
                    where I received my PhD in Biomedical Engineering. My focus is on the development, clinical implementation, and evaluation of custom-built generative AI tools for improvement of healthcare delivery. I have published extensively on these subjects, and was named Forbes 30 under 30 for this work."
          imageUrl: "picture2.jpg"
          imageWidth: 160
          imageHeight: 160
          imageTitle: Jonathan Huang
          buttons:
            - name: About
              url: about/
            - name: Publications
              url: papers/
            # - name: Courses
            #   url: courses/
            # - name: Data
            #   url: data/
            # - name: Tags
            #   url: tags/
            - name: Media
              url: media/
            - name: Resume
              url: cv_jh.pdf
            #- name: Archive
            #  url: archive/
    socialIcons:
        - name: Email
          url: mailto:jon@northwestern.edu
    
        - name: Google Scholar
          url: https://scholar.google.com/citations?user=ocRMrkEAAAAJ
        - name: LinkedIn
          url: https://linkedin.com/in/jon-h
        # - name: GitHub
        #   url: https://github.com/notjonhuang
        - name: ORCID
          url: https://orcid.org/0000-0002-3428-9952
      

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: false
        hiddenInSingle: true
    label:
      text: "Jonathan Huang"
      icon: favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn 
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
